baseURL = 'https://newstarwind.github.io/'
languageCode = 'zh-cn'
title = '祁新世界观'
theme = 'PaperMod'

[params]
    defaultTheme = "light" # light,dark,auto 切换深浅模式
    sectionPagesMenu = 'main'    
    # 重要：对应 content/a/ 和 content/b/ 文件夹的名字
    mainSections = ["evolution", "worldview"]

# 定义菜单 C：搜索
[[menus.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30 # 权重越大，位置越靠后

# 定义菜单 D：归档
[[menus.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 40

[outputs]
    home = ["HTML", "RSS", "JSON"] # 必须加上 JSON

# --- 导航栏菜单配置结束 ---